### PR TITLE
Implement new field "handlecount"

### PR DESCRIPTION
**Pull request by fraxken**
Hi,

As promised my pull-request to implement a new field "handlecount". I'm not very strong with C/C++, so dont hesitate to tell me if i'm doing something bad.

On my UNIX (centos) & Windows there is no performance regression or anything (seem ok to me).

Best Regards,
Thomas

### CODE REVIEW

**Comment by reklatsmasters** [comment]
@fraxken Linux build broken due to SIGSEV error. Could you fix it?

Errors on nodev4 due to incompatible version of one of module i'll fix later.

**Comment by fraxken** [comment]
Hmm i will take a look.

You should drop NodeJS 4 Support (not anymore supported^^).

**Comment by fraxken** [comment]
Ok, my co-worker was working on a full set of VM (all UNIX architectures). I will run/test on each of them and i will back to you (no SIGSEV on my local centos).

**Comment by fraxken** [comment]
The bug has been reproduced on our side (Ubuntu too). I'm working on a fix !

**Comment by fraxken** [comment]
Hmm... To be honest i was thinking that was a bug (but just some warnings). The build & tests are successfull.

https://gist.github.com/fraxken/9a2247987c7ce29ac93ecea19ced25a1

I love so much compiler warnings lol... I will take a look to understood what they mean.

**Comment by reklatsmasters** [comment]
@fraxken Anyway, thanks! I hope, you will fix it!

**Pull request closed without merging**
